import { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from '../../styles/components/Interface/Header.module.scss';
import Image from 'next/image';
import Link from 'next/link';

import { ToggleSwitch } from 'components/Buttons/toggleSwitch';


import Moon from 'public/interface/header/moon';

function Header() {
    // доставать данные из localStorag для toggleSwitch
    const [toggleSwitch, setToggleSwitch] = useState(false); // темная тема
    const [activeMenu, setActiveMenu] = useState(false); // кнопка меню
    const [activeHeader, setActiveHeader] = useState(false); // закрашивает header при скроле

    useEffect(() => {
        window.addEventListener('scroll', () => {
            if (pageYOffset > 55) {
                setActiveHeader(true);
            } else {
                setActiveHeader(false);
            }
        });
    });


    return (
        <>
        {/* темный задний фон, когда меню ативировано */}
         <div onClick={() => {setActiveMenu(!activeMenu)}} className={[styles.MenuBack, activeMenu ? styles.MenuBackActive : ''].join(' ')} ></div>

            <Head>
                <title>AudioBooks</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.Header}>
                <div className={styles.Container}>
                    <div className={styles.Wrapper}>
                        <div className={styles.Inner}>
                            <div className={styles.HeaderLogoCcontainer}>логотип</div>
                            <div className={styles.HeaderSearchContainer}>
                                <form className={styles.HeaderForm}>
                                    <input className={styles.HeaderSearch} name='search' placeholder='Поиск по книгам...' />
                                </form>
                            </div>
                            <div className={styles.HeaderMenuContainer}>
                                <div className={styles.HeaderTopicBtn}>
                                    <Moon />
                                </div>
                                <ul className={styles.HeaderMenu}>
                                    <li className={styles.HeaderMenuItem}>
                                        <Link href='/'><a className={styles.HeaderMenuLink}>Жанры</a></Link>
                                    </li>
                                    <li className={styles.HeaderMenuItem}>
                                        <Link href='/'><a className={styles.HeaderMenuLink}>Книжная полка</a></Link>
                                    </li>
                                    <li className={styles.HeaderMenuItem}>
                                        <Link href='/'><a className={styles.HeaderMenuLink}>Уведомления</a></Link>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className={styles.HeaderAccountLink}>
                            <Link href='/'>
                                <Image src="/interface/header/profile.svg" alt="Profile" width={40} height={40} />
                            </Link>
                        </div>
                        {/* <div className={styles.HeaderAuthContainer}>
                            <Link href='/'><div className={styles.HeaderSingIn}>Вход</div></Link>
                            <Link href='/'><div className={styles.HeaderLogIn}>Регестрация</div></Link>
                        </div> */}
                    </div>
                </div>
            </div>

        {/* header для мобильной версии */}
            <div className={[styles.HeaderM, activeHeader ? styles.HeaderMActive : ''].join(' ')}>
                <div className={styles.ContainerM}>
                    <div className={styles.WrapperM}>
                        <button onClick={() => {setActiveMenu(!activeMenu)}} className={styles.OpenMenuBtn}>
                            <Image src="/interface/header/leftBarWhiteTheme.svg" width="20px" height="20px"/>
                        </button>
                        <div className={styles.SearchBtn}>
                            <Image src="/interface/header/searchWhiteTheme.svg" width="20px" height="20px"/>
                        </div>
                    </div>
                </div>
            </div> 

           

            <div className={[styles.MobileMenu, activeMenu ? styles.MobileMenuActive : ''].join(' ')}>
                    <button onClick={() => {setActiveMenu(!activeMenu)}} className={styles.MobileMenuCloseBtn}>
                        <Image src="/interface/header/closeMenuBtn.svg" width="14px" height="14px"/>
                    </button>
                    <ul className={styles.MobileMenuContainer}>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Главная</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Профиль</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Жанры</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Книжная полка</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Темная тема</a></Link>
                            <ToggleSwitch toggleSwitch={toggleSwitch} setToggleSwitch={setToggleSwitch}/>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Уведомления</a></Link>
                        </li>   
                    </ul>
                </div>     
        </>
    )
}

export { Header };