import Head from 'next/head';
import styles from '../../styles/interface/Header.module.scss';
import Image from 'next/image';
import Link from 'next/link';

function Header() {
    return (
        <>
            <Head>
                <title>AudioBooks</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className={styles.Header}>
                <div className={styles.Container}>
                    <div className={styles.Wrapper}>
                        <div className={styles.Inner}>
                            <div className={styles.HeaderLogoCcontainer}>логотип</div>
                            <div className={styles.HeaderSearchContainer}>
                                <form className={styles.HeaderForm}>
                                    <input className={styles.HeaderSearch} name='search' placeholder='Поиск по книгам...' />
                                </form>
                            </div>
                            <div className={styles.HeaderMenuContainer}>
                                <div className={styles.HeaderTopicBtn}>
                                    <Image src="/interface/header/moon.svg" alt="Topic" width={28} height={28} />
                                </div>
                                <ul className={styles.HeaderMenu}>
                                    <li className={styles.HeaderMenuItem}>
                                        <Link href='/'><a className={styles.HeaderMenuLink}>Жанры</a></Link>
                                    </li>
                                    <li className={styles.HeaderMenuItem}>
                                        <Link href='/'><a className={styles.HeaderMenuLink}>Книжная полка</a></Link>
                                    </li>
                                    <li className={styles.HeaderMenuItem}>
                                        <Link href='/'><a className={styles.HeaderMenuLink}>Уведомления</a></Link>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className={styles.HeaderAccountLink}>
                            <Link href='/'>
                                <Image src="/interface/header/profile.svg" alt="Profile" width={40} height={40} />
                            </Link>
                        </div>
                        {/* <div className={styles.HeaderAuthContainer}>
                            <Link href='/'><div className={styles.HeaderSingIn}>Вход</div></Link>
                            <Link href='/'><div className={styles.HeaderLogIn}>Регестрация</div></Link>
                        </div> */}
                    </div>
                </div>
            </div>

            <div className={styles.HeaderM}>
                <div className={styles.ContainerM}>
                    <div className={styles.WrapperM}>
                        <div className={styles.OpenMenuBtn}>
                            <Image src="/interface/header/leftBarWhiteTheme.svg" width="20px" height="20px"/>
                        </div>
                        <div className={styles.SearchBtn}>
                            <Image src="/interface/header/searchWhiteTheme.svg" width="20px" height="20px"/>
                        </div>
                    </div>
                </div>

                <div className={styles.MobileMenu}>
                    <div className={styles.MobileMenuCloseBtn}>
                        <Image src="/interface/header/closeMenuBtn.svg" width="14px" height="14px"/>
                    </div>
                    <ul className={styles.MobileMenuContainer}>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Главная</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Профиль</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Жанры</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Книжная полка</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Темная тема</a></Link>
                        </li>
                        <li className={styles.MobileMenuItem}>
                            <Link href='/'><a className={styles.MobileMenuLink}>Уведомления</a></Link>
                        </li>   
                    </ul>
                </div>
            </div>


        </>
    )
}

export { Header };